Repository gtyrkicksin216/fulcrum-css, pull requests merged in 2019-06, with the labels that each got.

#20 Added FlexGrid to library
  .npmignore
  CHANGELOG.md
  flex-grid.png
  package.json
  scss/fulcrum.scss
  scss/modules/_flex-grid.scss
Labels: enhancement, feature

#21 Code Cleanup
  scss/modules/_font-color.scss
  scss/modules/_keyword-sizes.scss
  scss/modules/_margin.scss
  scss/modules/_padding.scss
Labels: Maint

#24 Overflow fix for u-flex-grid
  scss/modules/_flex-grid.scss
Labels: bug-fix

#26 Removed heading sizes
  scss/fulcrum.scss
Labels: bug-fix

#27 Release/0.3.1
  .stylelintrc
  CHANGELOG.md
  fulcrum-css-0.3.0.tgz
  fulcrum-css-0.3.1.tgz
  npm-shrinkwrap.json
  package.json
  scss/fulcrum.scss
  scss/modules/_align-self.scss
  scss/modules/_browser-compat.scss
  scss/modules/_element-floats.scss
  scss/modules/_elevation.scss
  scss/modules/_flex-align-items.scss
  scss/modules/_font-size.scss
  scss/modules/_font-weight.scss
  scss/modules/_margin.scss
  scss/modules/_padding.scss
  scss/modules/_rem-calcuation.scss
  scss/modules/_spacers.scss
  scss/modules/_text-alignment.scss
  scss/modules/_text-transform.scss
Labels: release

#28 Updated docs
  CHANGELOG.md
  CONTRIBUTING.md
  scss/modules/_keyword-sizes.scss
  scss/modules/_margin.scss
  scss/modules/_padding.scss
Labels: Maint
